### ISSUE TITLE
click handling

### ISSUE THREAD

**Issue by tadell** [chabokpush/chabok-client-android#1]
I want to know how notification click should be handled?

**Comment by Husseinhj** [comment]
Please read [here ](https://doc.chabokpush.com/android/notification-handling.html#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D8%A7%D8%B9%D9%84%D8%A7%D9%86)

I close this issue. If you have any question about this issue, Feel free and reopen
