### ISSUE TITLE
 فیلتر لوکیشن در پنل

### ISSUE THREAD

**Issue by HosseinEmadi** [chabokpush/chabok-client-android#10]
سلام.بنده کتابخونه های ذکر شده در داکیومنت رو برای پوش به لوکیشن خاص  به پروژه اضافه کردم اما با اینکه لوکیشن دستگاهم روشنه اما موقع فیلتر تو محدودم پوش ارسال نمیشه. لطفا راهنمایی کنید

**Comment by Husseinhj** [comment]
<p dir="rtl">آیا شما موقعیت مکانی کاربر را در <a href="https://doc.chabokpush.com/panel/subscribers.html#%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D9%85%DA%A9%D8%A7%D9%86%DB%8C">بخش جزئیات کاربر</a> مشاهده می‌کنید؟</p>
<p dir="rtl">در صورت عدم مشاهده موقعیت مکانی کاربر از <a href="https://doc.chabokpush.com/android/location-tracking.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%85%D9%88%D9%82%D8%B9%DB%8C%D8%AA-%D9%85%DA%A9%D8%A7%D9%86%DB%8C-%DB%8C%DA%A9%D8%A8%D8%A7%D8%B1-%D8%AF%D8%B1-%D8%B2%D9%85%D8%A7%D9%86-%D8%B4%D8%B1%D9%88%D8%B9-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87">پیاده‌سازی درست</a> و نحوه استفاده از موقعیت مکانی چابک اطمینان حاصل کنید.</p>

**Comment by Husseinhj** [comment]
آیا مشکل شما حل شده است؟
