### ISSUE TITLE
عمل نکردن نوتیفیکیشن هندلر در اندروید ۸ و بالاتر

### ISSUE THREAD

**Issue by farzin680** [chabokpush/chabok-client-android#11]
با سلام،

نوتیفیکیشن هندلرشما  در اندروید ۸ و بالاتر محدود شده و قابل استفاده نیست.
راه حل شما برای این مورد چیست ؟

**Comment by behrad** [comment]
> نوتیفیکیشن هندلرشما در اندروید ۸ و بالاتر محدود شده و قابل استفاده نیست.

منظورتون از نوتیفیکیشن هندلر کدوم بخشه دقیقن؟
و ممشکل مشخصتون چیه که نتونستین استفاده کنید ازش؟

**Comment by farzin680** [comment]
منظور همان برادکست رسیوری هست که در نمونه کدهای چابک برای دریافت پوش نوتیفیکیشن قرار داده اید : 

https://doc.chabokpush.com/android/rich_notification.html

**Comment by behrad** [comment]
لینکی که شما اشاره کردید بهش مربوط به مدیریت کلیک و نمایش نوتیفیکیشن‌های چند رسانه‌ای هست که روی ۸ فکر نمی کنم مشکلی داشته باشه

برای دریافت نوتیفیکیشن شما از متد
`onEvent`
استفاده می کنید که مستنداتش رو [اینجا](https://doc.chabokpush.com/android/chabok-messaging.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85-%DA%86%D8%A7%D8%A8%DA%A9) می تونید ببینید

برای مدیریت نحوه نمایش نوتیفیکیشن هم [اینجا](https://doc.chabokpush.com/android/notification-handling.html) رو ببینید


اگر مشکلی خاصی در استفاده از این‌ها دارید برای ما خطا و مشکلتون رو به طور مشخص بنویسید

**Comment by behrad** [comment]
مستندات به روز شده است و توضیحات لازم در مورد اندروید ۸ اضافه شد
[تنظیمات گریدل برای اندروید ۸](https://doc.chabokpush.com/android/gradle-setup.html#%D8%A7%D9%81%D8%B2%D9%88%D8%AF%D9%86-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87
)
و

[هندل کردن پوش نوتیفیکیشن دریافتی](https://doc.chabokpush.com/android/application-class.html#%DB%B2--%D8%AA%D8%B9%D8%B1%DB%8C%D9%81-%D8%B1%D8%B3%DB%8C%D9%88%D8%B1-pushmessagereceiver)
