### ISSUE TITLE
عدم دریافت نوتیفیکیشن در زمان بسته بودن برنامه 

### ISSUE THREAD

**Issue by farzin680** [chabokpush/chabok-client-android#12]
در مانیفست برنامه (جی-سی-ام رسیور) را اضافه کرده ایم و تنظیمات پنل چابک را نیز در مورد (جی-سس-ام) انجام داده ایم.
همچنین نمونه کدی که در صفحه
https://doc.chabokpush.com/android/notification-handling.html
قرار داده بودید را برای نمایش نوتیفیکیشن در حالت بسته بودن برنامه تغییر و پیاده سازی کردیم اما همچنان پیامی در زمان بسته بودن برنامه نمی رسد. در پنل چابک هم در حالت نرسیده قرار میگیرد تا زمانی که اپلیکیشن باز شود و پیام ها با همدیگر میرسند.

توضیح اینکه این مشکل در کلاینت آی او اس وجود ندارد.

**Comment by Husseinhj** [comment]
> اما همچنان پیامی در زمان بسته بودن برنامه نمی رسد. در پنل چابک هم در حالت نرسیده قرار میگیرد تا زمانی که اپلیکیشن باز شود

آیا appId را همانند [داکیومنت](https://doc.chabokpush.com/android/application-class.html#%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1%D9%87%D8%A7) اضافه کرده‌اید؟

زمانی که اپلیکیشن باز باشد و اپ به چابک متصل باشد از طریق کانکشن مستقیم به سرور چابک پیام را دریافت می‌کند. اگر اپلیکیشن بسته باشد پوش‌نوتیفیکیشن دریافت خواهد شد. علت عدم دریافت پوش‌نوتفیکیشن ممکن است درست نبودن یا عدم تنظیم بودن بخش تنظیمات پوش‌نوتیفیکیشن اندروید باشد و یا قرار ندادن سندرآی‌دی در اپ‌ای‌دی در اس‌دی‌کی باشد.

در بخش پیام‌ها در پنل می‌توانید در صورت بروز خطا در ارسال پوش‌نوتیفیکیشن نوع خطایی که با آن مواجه شده‌اید را مشاهده کنید و اگر خطایی داشته باشید برای ما اینجا قرار دهید تا راهنماییتان کنیم.

**Comment by farzin680** [comment]
متاسفانه خطایی نشان داده نمیشود و همچنان در حال ارسال نمایش داده میشود
مانند تصویری که در ضمیمه ارسال کرده ایم.

<img width="883" alt="screen shot 1397-06-14 at 10 39 32 am" src="https://user-images.githubusercontent.com/34789020/45074266-107ff780-b0f8-11e8-844d-011b83921696.png">

**Comment by behrad** [comment]
وقتی اپ رو باز می کنید ایا گوشی در پنل آنلاین میشه؟
اگر بله؟
آیا اون کاربر (یا دستگاهاش) روی کانالی که پیام روی اون ارسال شده عضو شده؟
این رو می تونید از طریق پنل تحقیق کنید (بخش جزییات کاربر یا دستگاه) و اینکه 
اگر خیر؟
آیا گوشی مورد نظر به وی‌پی‌ان ممکنه متصل باشه؟

**Comment by farzin680** [comment]
بله ، وقتی برنامه باز میشود پیام ها به برنامه رسیده و نمایش داده میشوند. و بله در کانال عضو شده است،
خیر به هیچ وی پی ان متصل نیست.

**Comment by behrad** [comment]
خب این تصویری که شما ارسال کردین برای وقتی هست که برنامه رو بسته دارین و هنوز باز نکردین

وقتی باز میکنید می رسند و تیک می خورن

تصویر نشون میده که نوتیفیکیشن‌های شما به موفقیت به اپل و گوگل ارسال شدن
بنابراین یا گوشی در حالت پراتکتت قرار میگیره که نوتیف ررو نشون نمیده
مدل گوشی چیه؟

در مورد این مسئله وان سیگنال به خوبی توضیح دادهه:
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

یا اینکه کد هندلر نوتیف شما به خطا دارهه میخوره
لاگ کامل در زمان بسته بودن اپ رو بفرستید درست همون موقع که نوتیف می فرستید

**Comment by behrad** [comment]
@farzin680 مشکل شما حل شد؟

**Comment by farzin680** [comment]
> @farzin680 مشکل شما حل شد؟

خیر متاسفانه

**Comment by behrad** [comment]
> خیر متاسفانه

صفحه [عیب یابی](https://doc.chabokpush.com/android/troubleshoot.html) چابک رو با دقت بخونید و موارد رو یک به یک توی اپ تون بررسی کنید حتمن مشکلتون حل میشه

اگر موفق نشدید می تونید درخواست بدید ما براتون نحوه فعال سازی و تنظیمات چاب رو براتون بازبینی کنیم

**Comment by sepehr13494** [comment]
سلام برای بنده هم همین مشکل پیش آمده درحالی که من تغییراتی در بخش پوش در کد ندادم ولی امروز دیدم که وقتی اپلیکیشن بسته هستش نوتیفیکیشن ارسال نمیشه و وقتی باز میشه تازه میاد نوتیفیکیشن.... 
این لینک هم کار نکرد..... 
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by Husseinhj** [comment]
<p dir="rtl">@sepehr13494 </p>
<blockquote dir="rtl">
<p dir="rtl">درحالی که من تغییراتی در بخش پوش در کد ندادم ولی امروز دیدم که وقتی اپلیکیشن بسته هستش نوتیفیکیشن ارسال نمیشه</p>
</blockquote>
<p dir="rtl">منظور شما این هست که قبلا کار می‌کرده ولی الان وقتی اپ بسته هست پوش‌نوتیفیکیشن دریافت نمی‌کنید؟</p>
<p dir="rtl">دقت کنید در بخش <a href="https://doc.chabokpush.com/panel/inbox.html#%D9%86%D9%85%D8%A7%D8%AF%D9%87%D8%A7%DB%8C-%D9%88%D8%B6%D8%B9%DB%8C%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85">پیام‌ها</a> در پنل در بخش <a href="https://doc.chabokpush.com/panel/inbox.html#%D9%BE%DB%8C%D8%A7%D9%85">جزئیات پیام</a>، چه خطایی (در صورت رخ‌دادن خطا) در بخش اعلان‌ها به شما نمایش داده می‌شود؟</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@sepehr13494 </p>
<blockquote dir="rtl">
<p dir="rtl">درحالی که من تغییراتی در بخش پوش در کد ندادم ولی امروز دیدم که وقتی اپلیکیشن بسته هستش نوتیفیکیشن ارسال نمیشه</p>
</blockquote>
<p dir="rtl">منظور شما این هست که قبلا کار می‌کرده ولی الان وقتی اپ بسته هست پوش‌نوتیفیکیشن دریافت نمی‌کنید؟</p>
<p dir="rtl">دقت کنید در بخش <a href="https://doc.chabokpush.com/panel/inbox.html#%D9%86%D9%85%D8%A7%D8%AF%D9%87%D8%A7%DB%8C-%D9%88%D8%B6%D8%B9%DB%8C%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85">پیام‌ها</a> در پنل در بخش <a href="https://doc.chabokpush.com/panel/inbox.html#%D9%BE%DB%8C%D8%A7%D9%85">جزئیات پیام</a>، چه خطایی (در صورت رخ‌دادن خطا) در بخش اعلان‌ها به شما نمایش داده می‌شود؟</p>

**Comment by sepehr13494** [comment]
<pre><code class="language-log">D/Event: No subscribers registered for event class com.adpdigital.push.ConnectionStatus
         No subscribers registered for event class f.h
V/ActivityThread: SVC-Destroying service com.adpdigital.push.PushService@574cc4f
W/Event: Subscriber to unregister was not registered before: class com.adpdigital.push.ah</code></pre>
<p dir="rtl">اینها ارور هایی هستش که وقتی اپ رو ترمینیت میکنم توی قسمت لاگ برام میاد</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@sepehr13494 این‌ها ارور نیستن فقط  log برای وضعیت چابک هست. حتما نسخه آخر چابک رو در تست‌های خودتون استفاده کنید.</p>
<p dir="rtl">شما روی چه دستگاه‌ و چه نسخه‌ از سیستم‌عامل اندروید تست می‌کنید؟</p>
<p dir="rtl">همچنین سوال بنده در بالا رو جواب ندادید که بتونم بهتر راهنماییتون کنم.</p>

**Comment by sepehr13494** [comment]
بله قبلا کار میکرده.. دستگاهم ASUS_X00GD اندروید 7.0 هستش.... در قسمت
جزئیات وقتی پیام رو میفرستم میگه هنوز تحویل داده نشده است.. و وقتی اپ رو
باز میکنم میگه پیام تحویل داده شده است.

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">دستگاهم ASUS_X00GD</p>
</blockquote>
<p dir="rtl">در بخش عیب‌یابی لطفا بخش <a href="https://dev.doc.chabokpush.com/android/troubleshoot.html#%D8%AF%D9%82%D8%AA-%DA%A9%D9%86%DB%8C%D8%AF-%DA%A9%D9%87-%D8%A7%D9%BE%D9%84%DB%8C%DA%A9%DB%8C%D8%B4%D9%86-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84%D8%AA-force-stop-%D9%86%D8%A8%D8%A7%D8%B4%D8%AF">force stop</a> رو مطالعه کنید چون دستگاه شما asus هست ممکنه که اپ بخاطر auto start manager دسترسی اپلیکیشن به پوش‌نوتیفیکیشن مقدور نباشد</p>
<blockquote dir="rtl">
<p dir="rtl">در قسمت جزئیات وقتی پیام رو میفرستم میگه هنوز تحویل داده نشده است</p>
</blockquote>
<p dir="rtl">پیام تحویل نشده به این معنی هست که وقتی اپلیکیشن شما باز باشه (به چابک متصل باشه) چابک به صورت خودکار پیام شما رو از طریق سوکت مستقیمی که چابک داره ارسال می‌کنه در صورت بسته بودن اپلیکیشن شما (عدم اتصال به چابک) اقدام به ارسال 
پوش‌نوتیفیکیشن میکنه. در مستندات پنل، <a href="https://dev.doc.chabokpush.com/panel/inbox.html#%D9%86%D9%85%D8%A7%D8%AF%D9%87%D8%A7%DB%8C-%D9%88%D8%B6%D8%B9%DB%8C%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85"> صفحه‌ جزئیات پیام</a> به این موضوع اشاره شده است، اگر پوش‌نوتیفیکیشن با موفقیت ارسال شود در بخش اعلان‌های این پیام دستگاه شما را نشان خواهد داد. اگر در ارسال پوش‌نوتیفیکیشن خطایی رخ دهد نیز در همان قسمت نشان داده خواهد شد. </p>
<p dir="rtl">اگر امکانش هست تصویری از جزئیات یک پیامی که در حالت بسته تحویل شما نمیشود در ایشو در اختیار ما قرار دهید. </p>
<p dir="rtl">آیا در اپلیکیشن شما sdk پوش‌نوتیفیکیشن دیگری هم وجود دارد که بررسی کنیم؟  </p>

**Comment by sepehr13494** [comment]
![image](https://user-images.githubusercontent.com/37529837/46571488-b4242800-c982-11e8-8168-e55e04a5ef5c.png)
من قسمت فورس استاپ رو مطالعه کردم دقیقا وقتی که سویپ میکنم از ریسنت اپس دیگه نوتیفیکیشن نمیاد تا دوباره اپ رو باز کنم. ولی مثلا تلگرام رو که سویپ میکنم از ریسنت میاد نوتیفیکیشنش

**Comment by Husseinhj** [comment]
> من قسمت فورس استاپ رو مطالعه کردم دقیقا وقتی که سویپ میکنم از ریسنت اپس دیگه نوتیفیکیشن نمیاد تا دوباره اپ رو باز کنم. ولی مثلا تلگرام رو که سویپ میکنم از ریسنت میاد نوتیفیکیشنش

تلگرام رو نمیشه با اپ‌های دیگه مقایسه کرد چون اپ‌های popular سیاست‌های force stop شامل اون‌‌ها نمیشه. مثل واتس‌اپ و توئیتر و ...

**Comment by sepehr13494** [comment]
بسیار عالی متوجه شدم خیلی متشکر از پشتیبانی خوبتون

**Comment by Husseinhj** [comment]
<p dir="rtl">شما از طریق دستگاه اندروید به یک دستگاه اندرویدی دیگه از طریق متد <code>publish</code> پیام ارسال می‌کنید؟</p>
<p dir="rtl">اگر به این شکل هست اگر امکانش هست نمونه کد که از <code>publish</code> استفاده میکنید رو میشه برای ما اینجا قرار بدید؟</p>

**Comment by sepehr13494** [comment]
در واقع هر از یک اپ به اپ دیگه هستش هردو اپ فعلا روی یک دستگاه هستش...

```java
private void sendData(Notification notification) {

        PushMessage myPushMessage = new PushMessage();

        myPushMessage.setBody("شما یک پیام دارید.");

        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("title", notification.getTitle());
            jsonObject.put("description", notification.getDescription());
            jsonObject.put("date", notification.getDate());
        } catch (JSONException e) {
            e.printStackTrace();
        }
        myPushMessage.setData(jsonObject);

        myPushMessage.setChannel("1");
        myPushMessage.setId(UUID.randomUUID().toString());
        myPushMessage.setUseAsAlert(true);

        chabok = ((MyApplication)getApplication()).getPushClient();

        chabok.publish(myPushMessage, new com.adpdigital.push.Callback() {
            @Override
            public void onSuccess(Object o) {
                //Add some codes to show publish was successfully done
                Toast.makeText(CreateNotificationActivity.this, "پیام با موفقیت ارسال شد.", Toast.LENGTH_SHORT).show();
                Log.d(TAG, "onSuccess: "+o.toString());
            }

            @Override
            public void onFailure(Throwable throwable) {
                //Add some codes for showing an error happened
                Toast.makeText(CreateNotificationActivity.this, "متاسفانه پیام ارسال نشد لطفا گزارش دهید.", Toast.LENGTH_SHORT).show();
                Log.d(TAG, "onFailure: "+throwable.getMessage());
            }

        });

    }
```

**Comment by Husseinhj** [comment]
<p dir="rtl">ممنون از قطعه کدی که فرستادید</p>
<p dir="rtl">شما نمیتونید به یک کاربر توی یک کانال <strong>public</strong> پیام ارسال کنید فقط برای ارسال به یک کانال <strong>private</strong> مشخص کردن شناسه کاربر منطقی هست. در واقع برای ارسال پیام به یک کانال عمومی شما باید از کد زیر استفاده کنید :</p>
<pre><code class="language-java">myPushMessage.setChannel(&quot;1&quot;);
myPushMessage.setUser(&quot;*&quot;);
myPushMessage.setUseAsAlert(true);</code></pre>
<p dir="rtl">برای ارسال پیام به یک کانال خصوصی یک کابر خاص باید کد زیر رو استفاده کنید:</p>
<pre><code class="language-java">myPushMessage.setChannel(PRIVATE_CHANNEL_NAME);
myPushMessage.setUser(USER_ID);
myPushMessage.setUseAsAlert(true);</code></pre>

<p dir="rtl">طبیعتا کاربر باید روی کانالی که برای آن پیام ارسال می‌کنید عضو باشد و کاربرانی پیام روی یک کانال را دریافت می‌کنند که روی آن کانال عضو باشند.</p>

**Comment by sepehr13494** [comment]
<pre><code class="language-java">private void sendData(MessageForHelper message) {

        PushMessage myPushMessage = new PushMessage();

        myPushMessage.setBody(&quot;پیام از طرف مدد کار&quot;);

        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put(&quot;title&quot;, message.getTitle());
            jsonObject.put(&quot;description&quot;, message.getDescription());
            jsonObject.put(&quot;date&quot;, message.getDate());
            jsonObject.put(&quot;helper&quot;, preferences.getString(&quot;helper_name&quot;,null));
            jsonObject.put(&quot;user_id&quot;, preferences.getString(&quot;user_id&quot;,null));
        } catch (JSONException e) {
            e.printStackTrace();
        }
        myPushMessage.setData(jsonObject);

        //myPushMessage.setChannel(&quot;1&quot;);
        myPushMessage.setId(UUID.randomUUID().toString());
        myPushMessage.setUseAsAlert(true);
        myPushMessage.setUser(&quot;user_&quot;+preferences.getString(&quot;user_id&quot;,null));

        chabok = ((MyApplication)getApplication()).getPushClient();

        chabok.publish(myPushMessage, new com.adpdigital.push.Callback() {
            @Override
            public void onSuccess(Object o) {
                //Add some codes to show publish was successfully done
                Toast.makeText(SendMessageActivity.this, &quot;پیام با موفقیت ارسال شد.&quot;, Toast.LENGTH_SHORT).show();
                Log.d(TAG, &quot;onSuccess: &quot;+o.toString());
            }

            @Override
            public void onFailure(Throwable throwable) {
                //Add some codes for showing an error happened
                Toast.makeText(SendMessageActivity.this, &quot;متاسفانه پیام ارسال نشد لطفا گزارش دهید.&quot;, Toast.LENGTH_SHORT).show();
                Log.d(TAG, &quot;onFailure: &quot;+throwable.getMessage());
            }

        });

    }</code></pre>
<p dir="rtl">این کدی هستش که برای فرستادن به یک یوزر خاص ازش استفاده میکنم</p>
<p dir="rtl">آیا استفاده از تابع ست یوزر در ارسال دسته جمعی ضروری هستش؟</p>
<p dir="rtl">الان فرق کد من با این که شما فرستادید یکی ست یوزر هست یکی هم این که من ست آیدی هم استفاده کردم که احتمالا طبق دستور عمل سایت خودتون بوده</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">myPushMessage.setUser(&quot;user_&quot;+preferences.getString(&quot;user_id&quot;,null));</p>
</blockquote>
<p dir="rtl">اینجا setUser به این معنی هست که پیام شما به چه کاربری ارسال بشه</p>
<blockquote dir="rtl">
<p dir="rtl">آیا استفاده از تابع ست یوزر در ارسال دسته جمعی ضروری هستش؟</p>
</blockquote>
<p dir="rtl">برای ارسال پیام به یک کانال عمومی نباید شما user رو با شناسه کاربر پر کنید، تو در یک کانال عمومی طبیعتا تمام کسانی که در آن عضو هستند پیام رو دریافت می‌کنند. پس شما فقط باید setUser رو برای یک کانال عمومی با * مقداردهی کنید.</p>
<blockquote dir="rtl">
<p dir="rtl">الان فرق کد من با این که شما فرستادید یکی ست یوزر هست یکی هم این که من ست آیدی هم استفاده کردم که احتمالا طبق دستور عمل سایت خودتون بوده</p>
</blockquote>
<p dir="rtl">بله نحوه مقدار دهی setUser برای کانال عمومی و خصوصی متفاوت که در کامنت قبلی توضیح داده شده که به چه شکل باید عمل کنید.
مقداردهی setId به عهده شما است و به منظور قرار دادن یک شناسه خوانا هست که در پنل بتونید پیام خودتون رو به راحتی  با جستجو پیدا کنید و یا از طریق api بررسی کنید.</p>

**Comment by farzin680** [comment]
> > خیر متاسفانه
> 
> صفحه [عیب یابی](https://doc.chabokpush.com/android/troubleshoot.html) چابک رو با دقت بخونید و موارد رو یک به یک توی اپ تون بررسی کنید حتمن مشکلتون حل میشه
> 
> اگر موفق نشدید می تونید درخواست بدید ما براتون نحوه فعال سازی و تنظیمات چاب رو براتون بازبینی کنیم

کاملا طبق صفحه عیب یابی پیش رفتم و البته مشکلی وجود نداشت که در مشکلات صفحه عیب یابی نوشته شده باشه اما مشکل هم حل نشد قاعدتا

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">کاملا طبق صفحه عیب یابی پیش رفتم و البته مشکلی وجود نداشت که در مشکلات صفحه عیب یابی نوشته شده باشه اما مشکل هم حل نشد قاعدتا</p>
</blockquote>
<p dir="rtl">چون شما دارید در متد buildNotification مقدار false  برمیگردانید که به این معنی است که اعلان نمایش داده نشود. لطفا کد خود را به شکل زیر تغییر دهید</p>

```java
@Override
public boolean buildNotification(ChabokNotification chabokNotification, NotificationCompat.Builder builder) {
      getDataFromChabokNotification(chabokNotification);

      return true;
}
```

**Comment by Husseinhj** [comment]
من این ایشو رو می‌بندم چون این مشکل در کد شما بوده و حل شده.
