### ISSUE TITLE
مجوزهای اضافه برای نمایش badge

### ISSUE THREAD

**Issue by mvonline** [chabokpush/chabok-client-android#13]
<p dir="rtl">با سلام 
به منظور نمایش <code>badge</code> بر روی ایکون برنامه مجوزهای ذیل می بایست به برنامه داده شود. </p>
<pre><code class="language-xml">me.everything.badger.permission.BADGE_COUNT_WRITE
me.everything.badger.permission.BADGE_COUNT_READ
com.oppo.launcher.permission.WRITE_SETTINGS
com.oppo.launcher.permission.READ_SETTINGS
android.permission.READ_APP_BADGE
com.huawei.android.launcher.permission.WRITE_SETTINGS
com.huawei.android.launcher.permission.READ_SETTINGS
com.huawei.android.launcher.permission.CHANGE_BADGE
com.majeur.launcher.permission.UPDATE_BADGE
com.anddoes.launcher.permission.UPDATE_COUNT
com.sonymobile.home.permission.PROVIDER_INSERT_BADGE
com.sonyericsson.home.permission.BROADCAST_BADGE
com.htc.launcher.permission.UPDATE_SHORTCUT
com.sec.android.provider.badge.permission.WRITE
com.sec.android.provider.badge.permission.READ</code></pre>
<p dir="rtl">لذا در برخی موارد که هدف توسعه دهندگان جلب اعتماد کاربر و گرفتن حداقل مجوزها از وی می باشد، مواجهه با این حجم زیاد از مجوز برای عملکرد نه چندان ضروری نمایش badge counter چندان مناسب به نظر نمی رسد. 
لذا فراهم کردن امکان نمایش اختیاری BADGE COUNTER از طریق SDK و حذف این مجوزها می تواند در کاهش حجم بی اعتمادی کاربر، روش مناسبی باشد. </p>

**Comment by Husseinhj** [comment]
<p dir="rtl">این ایشو به <a href="https://doc.chabokpush.com/android/features.html#%D8%A8%D8%B1%D8%AF%D8%A7%D8%B4%D8%AA%D9%86-%D9%85%D8%AC%D9%88%D8%B2%D9%87%D8%A7%DB%8C-%D8%BA%DB%8C%D8%B1-%D8%B6%D8%B1%D9%88%D8%B1%DB%8C-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%86%D8%B4%D8%A7%D9%86-badge-%D8%B1%D9%88%DB%8C-%D8%A2%DB%8C%DA%A9%D9%88%D9%86">داکیومنت</a> اضافه شده است.</p>
