### ISSUE TITLE
عدم اتصال به سرویس چابک

### ISSUE THREAD

**Issue by mahieskafi** [chabokpush/chabok-client-android#14]
<p dir="rtl">سلام</p>
<p align="right"  dir="rtl">من با اطلاعات حساب کاربری پروژه starter روی پروژه خودم connection status =CONNECTED دریافت می کنم اما با اطلاعات حساب کاربری خودم هرچه سعی می کنم connection status =DISCONNECTED است و به error زیر مواجه می شوم: </p>

```
 E/com.adpdigital.push.AdpPushClient: Cannot save device, Reason: Internal Server Error
    org.apache.http.client.HttpResponseException: Internal Server Error
        at a.f.sendResponseMessage(SourceFile:440)
        at a.e.run(SourceFile:2078)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by Husseinhj** [comment]
اطلاعات پنل خودتون رو به درستی تو پروژه وارد کردید؟

AppId, ApiKey, Username, Password

**Comment by mahieskafi** [comment]
AppId= MyAppName/SenderId
ApiKey= GCM API Key (in setting)
Username= Username(in access and tokens in panel)
Password = Password  (in access and tokens in panel)

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">ApiKey= GCM API Key (in setting)</p>
</blockquote>
<p dir="rtl">لطفا <a href="https://doc.chabokpush.com/android/application-class.html#%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1%D9%87%D8%A7">داکیومنت</a> رو مطالعه بفرمایید: 
</br>
ApiKey  همان SdkKey در پنل می‌باشد</p>
<p dir="rtl">AppId باید AppId که در پنل برای شما ساخته شده قرار داده شده است باشد</p>
<p dir="rtl">Username , Password هم در پنل قرار داده شده است.</p>
<p dir="rtl"><img src="https://user-images.githubusercontent.com/27139702/45404959-46802700-b676-11e8-92c8-a1c7dd997bc0.png" alt="image"></p>

**Comment by mahieskafi** [comment]
<p align="right"  dir="rtl">ممنونم  درست شد</p>
<p align="right"  dir="rtl">اما متاسفانه هیج جای داکیومنت به این مورد اشاره نشده بود و فقط گفته شده "مقادیر مربوط به حساب چابک خود را وارد نمایید".</p>
<p align="right"  dir="rtl">خیلی ممنون از راهنماییتون</p>
