### ISSUE TITLE
اتصال فایل به چابک

### ISSUE THREAD

**Issue by nedaRasuli** [chabokpush/chabok-client-android#17]
با سلام
من نیاز دارم زمانی که یک تغییری در سمت دیتابیس اتفاق میفتد ، یک نوتیفیکیشن برای کاربران ارسال شود
اما چگونه باید یک فایل 
php
را به پنل ارسال چابک متصل کنم
و فرمت آن و 
api
که در آن باید رعایت شود ، چگونه است
متشکرم

**Comment by Husseinhj** [comment]
<p dir="rtl">این ایشو بنظر برای این repo نیست و بهتره تو <a href="https://github.com/chabokpush/chabok-php-demo/issues">repo</a> مرتبط مطرح بشه</p>
<p dir="rtl"><a href="https://doc.chabokpush.com/rest-api/send-push.html">مستندات api</a> را مطالعه بفرمایید </p>
<p dir="rtl"><a href="https://api.doc.chabokpush.com/#/push">محیط تست api</a> را هم مشاهده بفرمایید</p>
<p dir="rtl">برای مشاهده <a href="https://doc.chabokpush.com/panel/settings.html#%D9%88%D8%A8-%D9%87%D9%88%DA%A9">webhook‌ها</a> مستندات پنل را مطالعه کنید.</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">اگر پاسخ سوال خودتون رو دریافت کردید، لطفا issue رو close کنین.</p>
