### ISSUE TITLE
Support for GoNative

### ISSUE THREAD

**Issue by MarziehQainian** [chabokpush/chabok-client-android#2]
با سلام
من با استفاده از متد 
```java
 private synchronized void initPushClient() {
        if (chabok == null) {
            chabok = AdpPushClient.init(
                    getApplicationContext(),
                    MainActivity.class,
                    YOUR_APP_ID,
                    YOUR_API_KEY,
                    SDK_USERNAME,
                    SDK_PASSWORD
            );
                   }
    }
```
و در کلاس mainActivity با استفاده از فرآیند ثبت کاربر
با استفاده از متد

 ```java
public void sendMobileTag(final String mobile) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {

                    try {
                        chabok=chabok.get();
                 
                        if(chabok.isConnected()){
                            String userId=mobile;
                        chabok.register(userId);}

                    } catch (Exception e) {

                        e.printStackTrace();
                    }

```
میخوام عملیات ثبت کاربر رو انجام بدم
اما اینجا تابع register  
عمل ثبت را انجام نمیدهد و بعد از این تابع
 اپ بشته میشه و پیغام
unfortunately, اسم اپ  has stopped 
نمایش داده میشه.

**Comment by Husseinhj** [comment]
شما نمونه کد نسخه اندروید مارو نگاه کنین ممکنه مشکل شما با دیدن نحوه استفاده درست از چابک حل بشه

https://github.com/chabokpush/chabok-starter-android

**Comment by behrad** [comment]
> اپ بشته میشه و پیغام
> unfortunately, اسم اپ has stopped

پیام خطا و استک ‌اش رو برای ما کپی کنید اینجا لطفن

**Comment by MarziehQainian** [comment]
No such instance method: 'io.gonative.android.MainActivity$PyramidBridge$1._register'

**Comment by behrad** [comment]
به نظر میاد شما از گونیتیو دارید استفاده می کنید
و ما هنوز چابک رو باهاش تست نکردیم ببینیم به چه صورت میشه ازش پشتیبانی کرد یا نه
به نظرم خودتون یه سرچ تو مستندات گونیتیو بکنید ببینیید چطور یک کتابخونه نیتیو اندرویید رو میشه فعال کرد

**Comment by MarziehQainian** [comment]
در داکیومنت گونیتو به جز وان سیگنال  برای ارسال پوش نوتیفیکیشن  لایبرری دیگه ای رو ندیدم ! 
اگر شما  راهنمایی برای استفاده از لایبرری خودتون دارین ممنون میشم که ارائه بدین
با تشکر.

**Comment by behrad** [comment]
ما پروژه گونیتیو دم دستی الان نداریم که توش تست کنیم و خطا‌ها رو بررسی کنیم
به نظرم شما یک پروژه خالی و نمونه از گونیتیو که چابک توش گذاشتین روی گیت‌هاب شیر کنید و باهم روش کار کنییم ببینیم داستان چیه

**Comment by ehsan-dev** [comment]
[AndroidManifest.txt](https://github.com/chabokpush/chabok-client-android/files/2603046/AndroidManifest.txt)

[Main.txt](https://github.com/chabokpush/chabok-client-android/files/2603052/Main.txt)


ارتباط با چابک برقرار است ... اما  پوش دریافت نمی شود.... فایل های پیکر بندی اپلود شده است... ممنون از راهنماییتون

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">ارتباط با چابک برقرار است ... اما پوش دریافت نمی شود.... فایل های پیکر بندی اپلود شده است... ممنون از راهنماییتون</p>
</blockquote>
<p dir="rtl">هنگامی که اپلیکیشن شما باز هست هم نوتیفیکیشنی نمایش داده نمی‌شود؟</p>
<p dir="rtl">در کد <code>Application</code> شما زمانی که شناسه کاربری <code>null</code> هست کاربر را مجدد برای اولین بار <code>register</code> نمی‌کنید؟</p>

```java
String userId = chabok.getUserId();
if (userId != null && !userId.isEmpty()) {
      chabok.register(userId);
}
```
<p dir="rtl">در صورت <code>null</code> بودن <code>userId</code> شما باید کاربر را با یک نام <code>register</code> کنید همانند کد زیر:</p>

```java
String userId = AdpPushClient.get().getUserId();

if (userId != null && !userId.isEmpty()) {
     AdpPushClient.get().register(userId);
} else {
     //If user is not registered verify the user and
     //call AdpPushClient.get().register("USER_ID") method at login page
     AdpPushClient.get().register("USER_ID");
}
```

**Comment by ehsan-dev** [comment]
بله... هنگامی که اپلیکیشن هم باز هست.. باز دریافت نمی شود

در صورت نال بودن یوزرآدی کاربر را ثبت نام میکنم مطابق کدی که قراردادید... ی لحظه جهت تست کد کامنت شده بود و مجددا برگرداندم... این قسمت اوکیه... مشکل از جای دیگه نمی تونه باشه؟

[dependenciesAppGradle.txt](https://github.com/chabokpush/chabok-client-android/files/2603140/dependenciesAppGradle.txt)
[dependenciesRoot.txt](https://github.com/chabokpush/chabok-client-android/files/2603142/dependenciesRoot.txt)

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">در صورت نال بودن یوزرآدی کاربر را ثبت نام میکنم مطابق کدی که قراردادید... ی لحظه جهت تست کد کامنت شده بود و مجددا برگرداندم... این قسمت اوکیه... مشکل از جای دیگه نمی تونه باشه؟</p>
</blockquote>
<p dir="rtl">یک <a href="https://github.com/chabokpush/chabok-starter-gonative/">پروژه با GoNative</a> برای شما ساخته‌ایم و با آن تست شده و پوش نوتیفیکیشن دریافت می‌شود.
لطفا پروژه chabok-starter-gonative را اجرا کنید و پس از تست موارد زیر را به درستی به پروژه خود اضافه کنید‌:</p>
<p dir="rtl">1) <a href="https://github.com/chabokpush/chabok-starter-gonative/blob/e74c99bfa4a2646ce6b638d8871427c1b8fc3c90/android/app/build.gradle#L60-L63">کتابخانه چابک</a> را به Gradle اضافه کنید</p>
<p dir="rtl">2) <a href="https://github.com/chabokpush/chabok-starter-gonative/blob/e74c99bfa4a2646ce6b638d8871427c1b8fc3c90/android/app/src/main/AndroidManifest.xml#L33-L43">GcmReceiver</a> را به فایل AndroidManifest.xml اضافه کنید</p>
<p dir="rtl">3) <a href="https://github.com/chabokpush/chabok-starter-gonative/blob/e74c99bfa4a2646ce6b638d8871427c1b8fc3c90/android/app/src/main/java/io/gonative/android/GoNativeApplication.java#L154-L225">کدهای راه‌اندازی</a> و <a href="https://github.com/chabokpush/chabok-starter-gonative/blob/e74c99bfa4a2646ce6b638d8871427c1b8fc3c90/android/app/src/main/java/io/gonative/android/GoNativeApplication.java#L51-L58">ثبت کاربر</a> را در کلاس Application قرار دهید</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@minaqainian 
@ehsan-dev </p>
<p dir="rtl">با توجه به نمونه کد <a href="https://github.com/chabokpush/chabok-starter-gonative/">chabok-starter-gonative</a>  برای  GoNative کتابخانه چابک امکان دریافت پوش‌نوتیفیکیشن را دارد.</p>
<p dir="rtl">لطفا برای بررسی و اجرا کد <a href="https://github.com/chabokpush/chabok-starter-gonative/">پروژه استارتر GoNative</a>
 را مشاهده کنید </p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@minaqainian 
@ehsan-dev </p>
<p dir="rtl">با توجه به نمونه کد <a href="https://github.com/chabokpush/chabok-starter-gonative/">chabok-starter-gonative</a>  برای  GoNative کتابخانه چابک امکان دریافت پوش‌نوتیفیکیشن را دارد.</p>
<p dir="rtl">لطفا برای بررسی و اجرا کد <a href="https://github.com/chabokpush/chabok-starter-gonative/">پروژه استارتر GoNative</a>
 را مشاهده کنید </p>
