### ISSUE TITLE
تغییر صدا و اضافه کردن ویبره به نوتیفیکیشن

### ISSUE THREAD

**Issue by mjyousefi** [chabokpush/chabok-client-android#20]
با سلام
می‌خواستم بدونم چطور میتونم صدای نوتیفیکیشن رو تغییر بدم؟
و اینکه چطور میتونم به نوتیفیکیشن‌ها ویبره اضافه کنم؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">می‌خواستم بدونم چطور میتونم صدای نوتیفیکیشن رو تغییر بدم؟</p>
</blockquote>
<p dir="rtl">فایل صدا رو در مسیر <code>/raw/YOUR_SOUND.mp3</code> قرار بدید و با استفاده از apiهای ارسال ما که در <a href="https://dev.doc.chabokpush.com/rest-api/send-push.html">بخش مستندات api</a> آمده اقدام به <a href="https://api.doc.chabokpush.com/">ارسال</a> کنید. در بخش مستندات api در مورد کلیدهای <strong>payload</strong> توضیح داده شده است.  یک نمونه جیسان برای شما قرار دادم:</p>
<pre><code class="language-json">{
  &quot;notification&quot;: {
    &quot;sound&quot;: &quot;YOUR_SOUND.mp3&quot;,
    &quot;title&quot;: &quot;TITLE&quot;,
    &quot;body&quot;: &quot;BODY&quot;
  },
  &quot;user&quot;: &quot;USER_ID&quot;,
  &quot;content&quot;: &quot;CONTENT&quot;
}</code></pre>
<blockquote dir="rtl">
<p dir="rtl">و اینکه چطور میتونم به نوتیفیکیشن‌ها ویبره اضافه کنم؟</p>
</blockquote>
<p dir="rtl">این بخش از <a href="https://doc.chabokpush.com/android/notification-handling.html#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%88-%DA%A9%D9%84%DB%8C%DA%A9-%D8%B1%D9%88%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86">مستندات</a> رو مطالعه کنید و قطعه کد زیر را در متد <code>buildNotification</code> قرار دهید</p>
<pre><code class="language-java">NotificationManager notificationManager = (NotificationManager) getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);

builder.setVibrate(new long[] { 1000, 1000, 1000, 1000, 1000 });

notificationManager.notify(0, builder.build());

return false;</code></pre>
