### ISSUE TITLE
مشکل با chabok-lib-geo

### ISSUE THREAD

**Issue by Mr-Hqq** [chabokpush/chabok-client-android#28]
<p dir="rtl">زمانی که به جای <code>chabok-lib</code> از <code>chabok-lib-geo</code> استفاده می کنم زمان انجام <code>register</code> اپ کرش می کنه</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا متن خطایی که توی logcat نشون داده میشه رو برامون اینجا قرار بدین.</p>
<blockquote dir="rtl">
<p dir="rtl">زمانی که به جای <code>chabok-lib</code> از <code>chabok-lib-geo</code> استفاده می کنم</p>
</blockquote>
<p dir="rtl">از کتابخونه موقعیت مکانی چابک استفاده می‌کنین؟</p>

**Comment by Mr-Hqq** [comment]
مشکلم با اضافه کردم api زیر به پروژه حل شد

|`compile 'com.android.installreferrer:installreferrer:1.0'`

**Comment by Mr-Hqq** [comment]
<p dir="rtl">مشکلم با اضافه کردن api زیر به پروژه حل شد</p>
<p dir="rtl"><code>compile &#39;com.android.installreferrer:installreferrer:1.0&#39;</code></p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@Mr-Hqq </p>
<p dir="rtl">لطفا قبل از آپدیت کتابخانه چابک، حتما <a href="https://doc.chabokpush.com/android/release-note.html">لیست تغییرات کتابخانه</a> رو مطالعه کنید</p>

**Comment by Mr-Hqq** [comment]
<p dir=rtl>
با عرض پوزش
چون سوالم دوباره در مورد کتابخونه موقعیت مکانی چابکه همین ایشیو رو دوباره باز کردم</p>
<p dir=rtl>الان من از این کتابخونه استفاده کردم اما هیچ اتفاقی رخ نمیده</p>
<p dir=rtl>و تو بخش موقعیت مکانی کاربر هیچ اطلاعاتی نمیاد</p>
<p dir=rtl>همه توابع رو امتحان کردم هیچ کدوم جواب نداد</p>

<p dir=rtl>اما از `add_listener` که استفاده می کنم تو بخش `onConnected` خروجی میده</p>
<p dir=rtl>اما هیچ اروری ندارم</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">همه توابع رو امتحان کردم هیچ کدوم جواب نداد</p>
</blockquote>
<p dir="rtl">اگر امکانش، قسمت‌هایی از کدهای مربوط به لوکیشن چابک رو که استفاده کردین در اینجا برای ما قرار بدین.</p>
<blockquote dir="rtl">
<p dir="rtl">اما از <code>add_listener</code> که استفاده می کنم تو بخش <code>onConnected</code> خروجی میده</p>
</blockquote>
<p dir="rtl">لوکیشن رو توی onConnected بهتون میده؟</p>

**Comment by Mr-Hqq** [comment]
```
        Intent intent = new Intent(getBaseContext(), LocationHostService.class);
        locationManager.addCallbackIntent(intent);
        locationManager.enableBackgroundMode();
        LocationParams params = new LocationParams.Builder().setAccuracy(LocationAccuracy.HIGH).setDistance(0).setInterval(500).build();
        locationManager.startLocationUpdates(params);
```

<p dir="rtl">بله لوکیشن میده</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@Mr-Hqq </p>
<p dir="rtl">کلاس سرویس رو توی فایل مانیفست و داخل تگ اپلیکیشن رجیستر کردین؟</p>
<pre><code class="language-xml">        &lt;service android:enabled=&quot;true&quot; android:name=&quot;.LocationHostService&quot; /&gt;</code></pre>

**Comment by Mr-Hqq** [comment]
<p dir="rtl">بله رجیستر کردم.</p>
<p dir="rtl">به نظرتون مشکل از کجاست؟</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">با emulator و فایل <a href="https://raw.githubusercontent.com/chabokpush/chabok-assets/master/run.gpx?sanitize=true">gpx</a> که ضمیمه کردم تست کنید در حالت foreground همچنین در پنل هم می‌تونین موقعیت مکانی کاربر رو مشاهده کنین</p>
<p dir="rtl">نسخه اندرویدی که روی اون تست می‌کنین چند هست؟</p>
<pre><code class="language-java">locationManger = LocationManager.init(getContext());
locationManger.enableBackgroundMode();
locationManger.addListener(this);

Intent intent = new Intent(getContext(), LocationHostService.class);
locationManger.addCallbackIntent(intent);

LocationParams params = new LocationParams.Builder().setAccuracy(LocationAccuracy.HIGH).setDistance(10).setInterval(500).build();
locationManger.startLocationUpdates(params);</code></pre>

**Comment by Mr-Hqq** [comment]
<p dir=rtl>هیچ اتفاقی نیوفتاد</p>
<p dir=rtl>چه تو امولاتور چه گوشی</p>
<p dir=rtl>نسخه 8 و 6 تست کردم</p>

![Image of Yaktocat](http://s9.picofile.com/file/8360646218/ccc.jpg)

**Comment by Mr-Hqq** [comment]
<p dir=rtl>من هنوز مشکلم حل نشده</p>
<p dir=rtl>خواهش می کنم کمک کنین تو این قضیه</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">من هنوز مشکلم حل نشده</p>
</blockquote>
<p dir="rtl">لطفا مطمئن بشید که location توی سرویس <a href="https://doc.chabokpush.com/android/location-tracking.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%85%D9%88%D9%82%D8%B9%DB%8C%D8%AA-%D9%85%DA%A9%D8%A7%D9%86%DB%8C-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84%D8%AA-kill">LocationHostService</a> میاد یا خیر؟</p>
<p dir="rtl">با استفاده از <a href="https://doc.chabokpush.com/android/location-tracking.html#%D9%85%D8%AA%D8%AF-addlistener">addListener</a> هم لوکیشنی دریافت نمی‌کنید؟</p>
<p dir="rtl">برای تست هم می‌تونی از<a href="https://github.com/chabokpush/chabok-demo-android"> اپلیکیشن دمو چابک</a> که قابلیت لوکیشن روی اون قرار داره استفاده کنید.</p>

**Comment by Husseinhj** [comment]
@Mr-Hqq 

مشکلتون حل شده؟
