### ISSUE TITLE
Add Sound to Android App

### ISSUE THREAD

**Issue by mgm93** [chabokpush/chabok-client-android#3]
سلام
چطور 
Sound 
به برنامه اضافه کنم؟

**Comment by behrad** [comment]
نحوه ارسال صدا در تنظیمات نوتیفیکیشن در این وب سرویس هستش:
https://api.doc.chabokpush.com/#/push/push_toUsers

اون صدایی که تو وب سرویس نام می برید باید تو اپلیکیشن‌تون باشه و برای نحوه اضافه کردن فایل صوتی به اپلیکیشن اندروید می تونید اینترنت رو سرچ کنید.

**Comment by mgm93** [comment]
طبق معمول عمل کردم اما نش
فایل رو داخل res/raw قرار دارم
به اسم myfile.wav 
بعد یه همچین داده ای فرستادم ولی صدا عوض نشد
```{
 "id": 0,
  "user": "0912*******",
  "content": "aaweq",
  "notification": {
    "title": "Simple New 2",
    "body": "test",
    "sound": "myfile.wav",
    "mediaType": "",
    "mediaUrl": "",
    "contentAvailable": true,
    "mutableContent": false,
    "category": ""
  },
  "data": null,
  "trackId": null,
  "inApp": false,
  "live": false,
  "useAsAlert": false,
  "alertText": null,
  "ttl": "0001-01-01T00:00:00",
  "idr": false,
  "silent": false
}```

**Comment by Husseinhj** [comment]
<div dir='rtl'> مشکل برای پخش صدا بود که در نسخه 2.11.3 حل شده است

سه‌شنبه (فردا) نسخه جدید منتشر خواهد شد

در سیستم عامل اندروید فایل باید در مسیر زیر قرار بدین:
</div>

` res/raw `

<div dir='rtl'>
و در پیلود هم از ارسال پسوند فایل خودداری کنید.

و فقط نام فایل در کلید sound ذکر شود
</div>
