### ISSUE TITLE
ارور Application ID

### ISSUE THREAD

**Issue by hosseinaryai** [chabokpush/chabok-client-android#30]
<p dir="rtl">با درود .. 
دوستان من این سیستم شما رو میخوام توی نرم افزارم پیاده سازی کنم .. 
با سیستم پوشه به راحتی و بدون دردسر انجام شد .. اما اینجا هر کاری میکنم باز یه جای دیگه اش گیر میده .. 
الان گیر داده به این :</p>
<pre><code>Caused by: java.lang.IllegalArgumentException: Application ID should be in `app-name/number` format</code></pre><p dir="rtl">برای چی آخه ؟ تمام مراحلو درست رفتن و ای دی ها هم درسته .. مشکل کجاست پس ؟</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">من این issue رو می‌بندم، اگر مشکلی در راه‌اندازی کتابخانه چابک داشتین issue فوق رو باز کنین.</p>
