### ISSUE TITLE
دریافت نوتیفیکیشن

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-client-android#31]
سلام وقت بخیر
نتیفیکیشن های دریافتی در نرم افزار موبایل زمانی که نرم افزار باز هست متن به صورت صحیح نمایش میدهد
اما زمانی که نرم فزار بسته باشد بجای متنی که ما ارسال کرده ایم اسم اکانت ما در پنل چابک را نمایش میدهد
برای رفع این مساله چه راه حلی وجود دارد؟
ممنون

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">اما زمانی که نرم فزار بسته باشد بجای متنی که ما ارسال کرده ایم اسم اکانت ما در پنل چابک را نمایش میدهد</p>
</blockquote>
<p dir="rtl">برای تغییر متن اعلان <a href="https://doc.chabokpush.com/panel/settings.html#%D8%A7%D8%B9%D9%84%D8%A7%D9%86-%D9%BE%DB%8C%D8%B4%D9%81%D8%B1%D8%B6">این بخش از مستندات پنل</a> رو مطالعه کنین.</p>
<p dir="rtl"> همچنین برای یکسان‌سازی متن اعلان و متن پیام چابک در ایجاد کمپین <a href="https://doc.chabokpush.com/panel/send.html#%D8%B3%DB%8C%D8%A7%D8%B3%D8%AA-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84">این بخش از مستندات پنل</a> رو مطالعه کنید</p>
<p dir="rtl"><a href="https://doc.chabokpush.com/rest-api/send-push.html#%D9%85%D8%AB%D8%A7%D9%84-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%B4%D8%AE%D8%B5%DB%8C-%D9%BE%DB%8C%D8%A7%D9%85-%DA%86%D8%A7%D8%A8%DA%A9-%D8%A8%D9%87-%DB%8C%DA%A9-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1">و با قرار دادن کلید useAsAlert در وب‌سرویس (api)</a> می‌تونین متن پیام با پوش‌نوتیفیکیشن رو یکسان کنید.</p>
<pre><code>curl -X POST \
&quot;https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=&lt;ACCESS_TOKEN&gt;&quot; \
-H &quot;accept: application/json&quot; \
-H &quot;Content-Type: application/json&quot; \
-d &quot;{ \&quot;user\&quot;: \&quot;Test\&quot;, \&quot;content\&quot;: \&quot;پرواز شما دچار نیم ساعت تاخیر شده است.\&quot;, \&quot;useAsAlert\&quot;: true}&quot;</code></pre>
