### ISSUE TITLE
مشکل دریافت دیتا نوتیف هنگام بسته بودن اپلیکیشن

### ISSUE THREAD

**Issue by HosseinEmadi** [chabokpush/chabok-client-android#4]
وقتی اپلیکیشن ران نیست دیتا نوتیفیکیشن رو از کجا بخونیم؟

**Comment by Husseinhj** [comment]
<p dir="rtl">issue شما بنظر hidden بوده و به تازگی دیده شده. و اینکه چون در جلسه حضوری این موضوع حل شده issue رو close می‌کنم</p>
<p dir="rtl">برای دریافت دیتا نوتیفیکیشن لطفا این بخش از <a href="https://doc.chabokpush.com/android/notification-handling.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-data-%D9%86%D9%88%D8%AA%DB%8C%D9%81%DB%8C%DA%A9%DB%8C%D8%B4%D9%86">مستندات</a> رو مطالعه کنید.</p>
