### ISSUE TITLE
چابک بر روی این مدل فاقد پرمیژن برای نشان دادن بچ می باشد.

### ISSUE THREAD

**Issue by behrad** [chabokpush/chabok-client-android#5]
E6633    Xperia Z5 dual    E6633    Sony

**Comment by mjyousefi** [comment]
<div dir='rtl'>
چابک از کتابخانه زیر استفاده می‌کند که پرمیشن تمامی گوشی‌ها را دارد.
</div>

<pre>
me.leolin:ShortcutBadger
</pre>

<div dir='rtl'>
من به مشکل مشابهی برخوردم
طبق داکیومنت وان سیگنال برای حذف بچ و پرمیشن‌های‌ آن، به صورت دستی آن‌ها در مانیفست پروژه خودم حذف کردم
به این شکل - به عنوان مثال برای سونی
</div>

```
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" tools:node="remove" />
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" tools:node="remove" />
```
<div dir='rtl'>
توضیحات آن در لینک زیر آمده است:
</div>

https://documentation.onesignal.com/docs/android-customizations#section-app-icon-badge-counts

<div dir='rtl'>
اما چابک از حذف پرمیشن بچ (حداقل به این شکل) پشتیبانی نمی‌کند.
با حذف دستورات بالا از مانیفست، پروژه به درستی کار کرد.

در کل اگر به صورت دستی پرمیشن‌های بچ تغییری نکنند مشکلی به وجود نمی‌آید.
اما همچنان نیاز به قابلیت حذف پرمیشن‌های بچ همچنان وجود دارد وشاید بهتر باشد که<code>issue</code> دیگری مطرح کرد.
</div>

**Comment by behrad** [comment]
duplicate of #13

**Comment by Husseinhj** [comment]
<p dir="rtl">@mj-developer  این موضوع رو بررسی کردیم و در داکیومنت هم ذکر کردیم</p>
<p dir="rtl">شما اگر دستگاه‌هایی رو که نمی‌خوایین براش دسترسی نشانه badge بدین به همون روشی که وان‌سیگنال توی داکش گفته می‌تونین دسترسی بج رو حذف کنین و دیگه بج برای اون دستگاه‌های نمایش داده نمیشه</p>

**Comment by behrad** [comment]
https://doc.chabokpush.com/android/gradle-setup.html

**Comment by mjyousefi** [comment]
@Husseinhj 
ممنون از شما
البته هنوز مشکل هست!
چون با این کار فقط پرمیژن حذف میشه و موقع نمایش بج در مدل گوشی‌هایی که نیاز به پرمیژن دارند کرش می‌کنه 
چون پرمیژنی که نیاز دارن دریافت نشده)
وان سیگنال علاوه بر کد حذف پرمیژن که داخل داکیومنت نوشتید مقدار زیر رو هم به مانیفست اضافه می‌کنه:

```
   <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
```

من نسخه‌ی 2.13.1 رو روی گوشی E6633 Xperia Z5 dual E6633 Sony نصب کردم و کرش کرد.

**Comment by Husseinhj** [comment]
<p dir="rtl">چون تستی که من روی E6833  انجام دادم و permissionها رو حذف کردم بازم هم کار کرد و کرش نکرد</p>
<p dir="rtl"><a href="https://github.com/leolin310148/ShortcutBadger">ShortcutBadger</a> که شما با اون تست می‌کنین چه نسخه‌ای هست؟</p>

**Comment by mjyousefi** [comment]
از نسخه 1.1.22
در هر صورت من فعلا حذف نکردم تا مشکلی پیش نیاد

**Comment by Husseinhj** [comment]
<p dir="rtl">‌اگر امکانش هست، log خطایی که برای permission میگیری هنگامی که permission حذف هست رو اینجا برامون قرار میدی؟</p>

**Comment by Husseinhj** [comment]
من این ایشو رو باز می‌کنم مجددا @mj-developer 
و دوباره بررسی می‌کنم

**Comment by Husseinhj** [comment]
<p dir="rtl">@mj-developer در نسخه <a href="https://github.com/chabokpush/chabok-client-android/releases/tag/v2.13.3">۲.۱۳.۳</a> این موضوع حل شده و می‌توانید با قرار دادن مقدار زیر در فایل manifest امکان نمایش badge را غیرفعال کنید:</p>

```xml
<meta-data android:name="com.adpdigital.push.client.BadgeCount" android:value="DISABLE" />
```
