### ISSUE TITLE
دریافت نشدن پوش وقتی اپ باز نیست

### ISSUE THREAD

**Issue by AliINL** [chabokpush/chabok-client-android#6]
<div dir='rtl'>
من از توی پنل با تنظیمات پیش فرض پوش ارسال میکنم
اما پیام تا وقتی که اپ باز نشه تحویل داده نمیشه

توی کلاس اپلیکیشن چابک رو مقداردهی اولیه کردم(اسم اکتیویتی که بعد از کلیک روی نوتیفیکیشن باز بشه و اپ آیدی و ای پی آی کی و یوزرنیم و پسورد) رو ست کردم
همچنین رجیستر هم در کلاس اپلیکیشن انجام دادم

در پوش اکتیویتی(قرار هست بعد از کلیک روی نوتیفیکیشن این اکتیویتی باز بشه) دستور:

<div dir='ltr'>
<pre>
private AdpPushClient client;
client = AdpPushClient.get();
client.addListener(this);
</pre>
</div>

و
<div dir='ltr'>
<pre>
public void onEvent(PushMessage message){   
   Toast.makeText(this,message.getAlertText(),Toast.LENGTH_LONG).show();
}
</pre>
</div>

و

<div dir='ltr'>
<pre>
@Override
public void onTerminate() {
     if (chabok != null)
         chabok.dismiss();
     super.onTerminate();
}
</pre>
</div>

قرار دادم

البته گفتم شاید مشکل از این آخرین دستور باشه، حذفش کردم اما مشکل حل نشد

ممنون میشم راهنمایی بفرمایید مشکل کجاست
</div>

**Comment by Husseinhj** [comment]
> من از توی پنل با تنظیمات پیش فرض پوش ارسال میکنم اما پیام تا وقتی که اپ باز نشه تحویل داده نمیشه
<div dir='rtl'>
پیام چابک زمانی تحویل داده میشه که کاربر اپ رو باز کنه، اگر منظور شما دریافت پوش‌نوتیفیکیشن هست، می‌تونین از<code>NotificationHandler</code> چابک استفاده کنین.
</div>

**Comment by behrad** [comment]
> من از توی پنل با تنظیمات پیش فرض پوش ارسال میکنم اما پیام تا وقتی که اپ باز نشه تحویل داده نمیشه

تحویل داده نمیشه؟ یا اینکه نوتیفیکیشن نمایش داده نمیشه؟

**Comment by farzin680** [comment]
با سلام
این 

> نوتیفیکیشن هندلر

 شما در اندروید ۸ و بالاتر محدود شده و قابل استفاده نیست.
راه حل شما برای این مورد چیست ؟

**Comment by behrad** [comment]
تکراری شبیه https://github.com/chabokpush/chabok-client-android/issues/11
