### ISSUE TITLE
هندل کردن دیتای پوش

### ISSUE THREAD

**Issue by AliINL** [chabokpush/chabok-client-android#7]
سلام
وقت بخیر

ما در سیستم‌های نوتیفیکیشن پیشین گذشته که کار میکردیم ۲ تا کلاس مجزا به نام‌های

> notificationReciver
> notificationOpenHandler

داشتیم

ما در پروژمون انواع متفاوت پوش با محتوای متفاوت و با اکشن های متفاوت داریم

وقتی پوش میاد
ما محتوای پوش رو انتقال میریم به کلاسی به نام

> datamanager

تا این کلاس ببینه این پوش از چه نوعی با چه محتوایی و چه اکشنی است تا کار درست رو انجام بده

دقت کنید وقتی کاربر چه بیرون اپ باشه و چه توی اپ باشه براش نوتیف بیاد و روی نوتیف کلیک کنه هیچ اکتیویتی نباید باز بشه بلکه باید اطلاعات نوتیفیکیشن باید  به 

> datamanager 

پاس داده بشه و این کلاس تصمیم بگیره چه اکتیویتی رو نمایش بده
در گذشته ما این رو با 

>  notificationOpenHandler

هندل میکردیم

اما توی چابک نمیدونم باید چیکار کنم

ممنون میشم راهنمایی کنید

**Comment by Husseinhj** [comment]
<div dir='rtl'>
با توجه به توضیحاتی که در مستندات ارائه شده، شما می‌توانید نمایش اعلان روی پیام چابک را غیرفعال کنید و خودتان اقدام به ساخت و نمایش نوتیفیکیشن روی پیام چابک کنید. چون فرآیند هدایت کاربر به صفحه مناسب براساس کلیک روی نوتیفکیشن برای شما به صورت <code>async</code> هست
</div>
