### ISSUE TITLE
عدم نمایش پوش نوتیفیکیشن زمانیکه اپ بسته است

### ISSUE THREAD

**Issue by mjyousefi** [chabokpush/chabok-client-android#9]
پوش نوتیفیکیشن ارسالی تا زمانی که برنامه بسته است نمایش داده نمی‌شود و به محض باز شدن اپ تمام نوتیفیکیشن‌ها نمایش داده می‌شوند.
چطور در این حالت نوتیفیکیشن را نشان دهم؟
با تشکر

**Comment by Husseinhj** [comment]
> پوش نوتیفیکیشن ارسالی تا زمانی که برنامه بسته است نمایش داده نمی‌شود
<div dir='rtl'>
آیا به هنگام ارسال پیام چابک از پنل یا با api سیاست تحویل را روی پیام درون برنامه‌ای قرار داده‌اید؟

آیا تنظیمات پوش‌نوتیفکیشن اندروید را در پنل اعمال کرده‌اید؟
</div>

> به محض باز شدن اپ تمام نوتیفیکیشن‌ها نمایش داده می‌شوند

<div dir='rtl'>
پیام چابک زمانی که اپ باز باشد بخاطر کانکشن مستقیمی که چابک دارد پیام را از این طریق به اپلیکیشن ارسال می‌کند. دلیل نگرفتن نوتیفکیشن در حالت بسته بودن اپ می‌تواند یکی از شرایط بالا باشد.

دقت کنید حتما در فایل AndroidManifest.xml مقدار GcmReceiver اضافه شده باشد
</div>

**Comment by farzin680** [comment]
در مانیفست برنامه (جی-سی-ام رسیور) را اضافه کرده ایم و تنظیمات پنل چابک را نیز در مورد (جی-سس-ام) انجام داده ایم.
همچنین نمونه کدی که در صفحه
https://doc.chabokpush.com/android/notification-handling.html
قرار داده بودید را برای نمایش نوتیفیکیشن در حالت بسته بودن برنامه تغییر و پیاده سازی کردیم اما همچنان پیامی در زمان بسته بودن برنامه نمی رسد. در پنل چابک هم در حالت نرسیده قرار میگیرد تا زمانی که اپلیکیشن باز شود و پیام ها با همدیگر میرسند.

توضیح اینکه این مشکل در کلاینت آی او اس وجود ندارد.

**Comment by behrad** [comment]
@mj-developer آیا مشکل شما حل شده است؟

**Comment by farzin680** [comment]
> @mj-developer آیا مشکل شما حل شده است؟

خیر

**Comment by behrad** [comment]
duplicate of #12
